[package]
name = "metabonding-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["Dorin Marian Iancu, dorin.iancu@multiversx.com"]

[dev-dependencies]

[dependencies.metabonding]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.45.1"
